name: Build and Release EXE

on:
  push:
    tags:
      - 'v*' # این اکشن فقط زمانی اجرا میشه که تگ ورژن جدید بزنی (مثلا v1.0.1)

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter requests urllib3 psutil pillow pyzbar

      - name: Build EXE with PyInstaller
        working-directory: ./maim
        run: |
          # اضافه کردن --collect-all pyzbar برای حل مشکل فایل‌های dll مربوط به QR Code
          pyinstaller --onefile --noconsole --collect-all customtkinter --collect-all pyzbar --name NetTools_Pro main.pyw

      - name: Create ZIP Package
        working-directory: ./maim
        run: |
          Copy-Item -Path .\xray -Destination .\dist\xray -Recurse
          Compress-Archive -Path .\dist\* -DestinationPath .\NetTools_Pro_Release.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: maim/NetTools_Pro_Release.zip 
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
