name: Build and Release EXE

on:
  push:
    tags:
      - 'v*' # این اکشن فقط زمانی اجرا میشه که تگ ورژن جدید بزنی (مثلا v1.0.2)

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest # ساخت روی سرور ویندوز برای خروجی exe

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # اضافه شدن psutil, pillow, pyzbar برای مانیتورینگ و اسکنر کیوآرکد
          pip install pyinstaller customtkinter requests urllib3 psutil pillow pyzbar

      - name: Build EXE with PyInstaller
        # ربات دقیقاً وارد پوشه maim شما می‌شود
        working-directory: ./maim
        run: |
          # استفاده از --collect-all برای جلوگیری از کرش کردن گرافیک برنامه در نسخه EXE
          pyinstaller --onefile --noconsole --collect-all customtkinter --name NetTools_Pro main.pyw

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          # مسیر خروجی بر اساس پوشه maim تنظیم شد
          files: maim/dist/NetTools_Pro.exe 
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
