name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: '🏷 Version tag'
        required: true
        default: 'v9.6'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dnspython cryptography pyinstaller customtkinter requests urllib3 psutil pillow pyzbar pystray

      - name: Build EXE with PyInstaller
        working-directory: ./maim
        run: |
          pyinstaller --onefile --noconsole --uac-admin --icon=icon.ico `
            --add-data "cores;cores" `
            --collect-all customtkinter `
            --collect-all pyzbar `
            --collect-all cryptography `
            --hidden-import pystray `
            --hidden-import dns.resolver `
            --hidden-import dns.exception `
            --hidden-import dns.flags `
            --hidden-import dns.edns `
            --hidden-import dns.query `
            --hidden-import dns.message `
            --name NetTools_Pro main.pyw

      - name: Create ZIP Package
        working-directory: ./maim
        run: |
          if (Test-Path .\xray) { Copy-Item -Path .\xray -Destination .\dist\xray -Recurse -Force }
          Compress-Archive -Path .\dist\* -DestinationPath .\NetTools_Pro_Release.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || '' }}
          files: maim/NetTools_Pro_Release.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
