name: Build Windows EXE

on:
  push:
    tags:
      - 'v*' # این اکشن فقط زمانی اجرا میشه که یک تگ مثل v1.0.0 بسازید

jobs:
  build:
    runs-on: windows-latest # چون فایل exe میخوایم، روی سرور ویندوز اجراش میکنیم

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # نسخه پایدار پایتون

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconfirm --name CloudflareScanner bpb2.py

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/CloudflareScanner.exe
          generate_release_notes: true
